---
# Playbook to change Wazuh admin password
# Usage: ansible-playbook -i inventory playbooks/change-admin-password.yml -e "new_admin_password=YourNewPassword"

- hosts: wi1
  become: yes
  become_user: root
  vars_prompt:
    - name: new_admin_password
      prompt: "Enter new admin password"
      private: yes
      confirm: yes

  tasks:
    - name: Generate password hash
      shell: |
        echo "{{ new_admin_password }}" | /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
      register: password_hash
      no_log: true

    - name: Backup current internal_users.yml
      copy:
        src: /etc/wazuh-indexer/opensearch-security/internal_users.yml
        dest: /etc/wazuh-indexer/opensearch-security/internal_users.yml.backup
        remote_src: yes
        mode: '0644'

    - name: Update admin password hash in internal_users.yml
      replace:
        path: /etc/wazuh-indexer/opensearch-security/internal_users.yml
        regexp: '^(admin:\s*\n\s*hash:\s*).*$'
        replace: '\1''{{ password_hash.stdout | trim }}'''
        backup: no

    - name: Apply security configuration changes
      shell: |
        /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
          -cd /etc/wazuh-indexer/opensearch-security/ \
          -icl -nhnv \
          -cacert /etc/wazuh-indexer/certs/root-ca.pem \
          -cert /etc/wazuh-indexer/certs/admin.pem \
          -key /etc/wazuh-indexer/certs/admin-key.pem
      register: security_update
      changed_when: "'Done' in security_update.stdout"

    - name: Display result
      debug:
        msg: "Admin password has been changed successfully!"
      when: security_update.rc == 0

    - name: Update dashboard configuration if needed
      lineinfile:
        path: /etc/wazuh-dashboard/opensearch_dashboards.yml
        regexp: '^opensearch\.password:'
        line: "opensearch.password: {{ new_admin_password }}"
        state: present
      delegate_to: "{{ groups['dashboard'][0] if 'dashboard' in groups else '10.250.32.110' }}"
      when: security_update.rc == 0
